<?php
// This file is part of Moodle - http://moodle.org/

namespace theme_iomad_learning\local;

/**
 * Semantic Moodle and IOMAD icon mappings.
 *
 * Every resolved value is a reviewed symbol from the theme-owned SVG sprite.
 * The resolver deliberately uses component and action semantics rather than
 * copying icon filenames from upstream templates.
 *
 * @package    theme_iomad_learning
 * @copyright  2026 IOMAD Learning
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
final class icon_catalog {
    /**
     * Project components which must always have a reviewed icon.
     */
    private const PROJECT_COMPONENTS = [
        'block_dash' => 'dashboard',
        'block_gamification_telemetry' => 'trophy',
        'block_iomaddashboard' => 'dashboard',
        'block_iomadpagebuilder' => 'workflow',
        'block_tenantform' => 'form',
        'format_designer' => 'palette',
        'format_iomadvideo' => 'play',
        'local_aicoursecreator' => 'wand',
        'local_global_events' => 'activity',
        'local_institutionpack' => 'package',
        'local_iomad' => 'building',
        'local_iomad_h5p_bridge' => 'puzzle',
        'local_iomad_scorm_gen' => 'package',
        'local_iomadcommerce' => 'store',
        'local_iomadconnect' => 'link',
        'local_iomadpagebuilder' => 'workflow',
        'local_rapidgrader' => 'list',
        'local_tenantanalytics' => 'report',
        'local_tenantmaster' => 'institution',
        'mod_tenantform' => 'form',
        'theme_iomad_learning' => 'palette',
        'tool_courserating' => 'star',
        'tool_iomadmonitor' => 'monitor',
    ];

    /**
     * High-use Moodle and IOMAD component mappings.
     */
    private const COMPONENT_ICONS = [
        'auth_iomadoidc' => 'shield',
        'availability_company' => 'institution',
        'block_iomad_company_admin' => 'building',
        'block_iomad_learningpath' => 'workflow',
        'block_iomad_microlearning' => 'activity',
        'block_iomad_mycourses' => 'course',
        'block_iomad_reports' => 'report',
        'enrol_license' => 'key',
        'mod_assign' => 'edit',
        'mod_bigbluebuttonbn' => 'video',
        'mod_book' => 'book',
        'mod_choice' => 'list',
        'mod_data' => 'database',
        'mod_feedback' => 'form',
        'mod_folder' => 'folder',
        'mod_forum' => 'message',
        'mod_glossary' => 'book',
        'mod_h5pactivity' => 'puzzle',
        'mod_imscp' => 'archive',
        'mod_iomadcertificate' => 'certificate',
        'mod_label' => 'tag',
        'mod_lesson' => 'course',
        'mod_lti' => 'puzzle',
        'mod_page' => 'file',
        'mod_qbank' => 'help',
        'mod_quiz' => 'list',
        'mod_resource' => 'download',
        'mod_scorm' => 'package',
        'mod_subsection' => 'list',
        'mod_trainingevent' => 'calendar',
        'mod_url' => 'link',
        'mod_wiki' => 'book',
        'mod_workshop' => 'group',
        'repository_dropbox' => 'cloud',
        'repository_nextcloud' => 'cloud',
        'repository_onedrive' => 'cloud',
    ];

    /**
     * Fallbacks by Moodle plugin type.
     */
    private const TYPE_FALLBACKS = [
        'aiplacement' => 'wand',
        'aiprovider' => 'brain',
        'antivirus' => 'shield',
        'assignfeedback' => 'message',
        'assignsubmission' => 'upload',
        'auth' => 'key',
        'availability' => 'filter',
        'block' => 'dashboard',
        'booktool' => 'book',
        'cachestore' => 'database',
        'communication' => 'message',
        'contenttype' => 'file',
        'customfield' => 'settings',
        'datafield' => 'list',
        'dataformat' => 'fileExport',
        'editor' => 'edit',
        'enrol' => 'userAdd',
        'factor' => 'shield',
        'fileconverter' => 'fileExport',
        'filter' => 'filter',
        'format' => 'list',
        'gradeexport' => 'fileExport',
        'gradeimport' => 'fileImport',
        'gradepenalty' => 'alert',
        'gradereport' => 'chart',
        'gradingform' => 'form',
        'local' => 'puzzle',
        'logstore' => 'clock',
        'media' => 'play',
        'message' => 'message',
        'mlbackend' => 'brain',
        'mod' => 'puzzle',
        'paygw' => 'creditCard',
        'portfolio' => 'folder',
        'profilefield' => 'user',
        'qbank' => 'help',
        'qbehaviour' => 'list',
        'qformat' => 'fileImport',
        'qtype' => 'help',
        'quiz' => 'list',
        'quizaccess' => 'shield',
        'report' => 'report',
        'repository' => 'folder',
        'scormreport' => 'report',
        'search' => 'search',
        'smsgateway' => 'message',
        'theme' => 'palette',
        'tiny' => 'edit',
        'tool' => 'settings',
        'webservice' => 'code',
        'workshopallocation' => 'group',
        'workshopeval' => 'chart',
        'workshopform' => 'form',
    ];

    /**
     * Exact action and status mappings.
     */
    private const ICON_OVERRIDES = [
        'block_iomad_learningpath:learningpath' => 'workflow',
        'block_iomad_mycourses:courses' => 'course',
        'booktool_print:book' => 'book',
        'booktool_print:chapter' => 'file',
        'core:a/add_file' => 'add',
        'core:a/download_all' => 'download',
        'core:a/setting' => 'settings',
        'core:e/cancel' => 'close',
        'core:e/copy' => 'copy',
        'core:e/cut' => 'cut',
        'core:e/redo' => 'refresh',
        'core:e/save' => 'save',
        'core:e/undo' => 'refresh',
        'core:e/emoticons' => 'smile',
        'core:i/calendar' => 'calendar',
        'core:i/contentbank' => 'archive',
        'core:i/course' => 'course',
        'core:i/dashboard' => 'dashboard',
        'core:i/emojicategoryactivities' => 'trophy',
        'core:i/emojicategoryanimalsnature' => 'leaf',
        'core:i/emojicategoryflags' => 'flag',
        'core:i/emojicategoryfooddrink' => 'coffee',
        'core:i/emojicategoryobjects' => 'lightbulb',
        'core:i/emojicategorypeoplebody' => 'group',
        'core:i/emojicategoryrecent' => 'clock',
        'core:i/emojicategorysmileysemotion' => 'smile',
        'core:i/emojicategorysymbols' => 'shapes',
        'core:i/emojicategorytravelplaces' => 'mapPin',
        'core:i/group' => 'group',
        'core:i/home' => 'home',
        'core:i/info' => 'info',
        'core:i/loading' => 'spinner',
        'core:i/loading_small' => 'spinner',
        'core:i/navigationitem' => 'menu',
        'core:i/next' => 'chevronRight',
        'core:i/permissions' => 'shield',
        'core:i/previous' => 'chevronLeft',
        'core:i/req' => 'required',
        'core:i/restore' => 'restore',
        'core:i/settings' => 'settings',
        'core:i/trash' => 'trash',
        'core:i/user' => 'user',
        'core:i/viewcategory' => 'eye',
        'core:i/withsubcat' => 'folderPlus',
        'core:book' => 'book',
        'core:fp/view_icon_active' => 'dashboard',
        'core:fp/view_tree_active' => 'list',
        'core:req' => 'required',
        'core:t/add' => 'add',
        'core:t/cohort' => 'group',
        'core:t/collapsed' => 'chevronRight',
        'core:t/delete' => 'trash',
        'core:t/down' => 'arrowDown',
        'core:t/download' => 'download',
        'core:t/documentation' => 'book',
        'core:t/edit' => 'edit',
        'core:t/expanded' => 'chevronDown',
        'core:t/hide' => 'eyeOff',
        'core:t/left' => 'arrowLeft',
        'core:t/lock' => 'lock',
        'core:t/message' => 'message',
        'core:t/markasread' => 'check',
        'core:t/move' => 'workflow',
        'core:t/print' => 'print',
        'core:t/reload' => 'refresh',
        'core:t/right' => 'arrowRight',
        'core:t/search' => 'search',
        'core:t/life-ring' => 'help',
        'core:t/show' => 'eye',
        'core:t/switch_minus' => 'eyeOff',
        'core:t/switch_plus' => 'eye',
        'core:t/unlock' => 'key',
        'core:t/up' => 'arrowUp',
        'core:t/upload' => 'upload',
        'enrol_license:withkey' => 'key',
        'enrol_license:withoutkey' => 'lock',
        'mod_book:add' => 'add',
        'mod_book:chapter' => 'file',
        'mod_scorm:browsed' => 'eye',
        'mod_scorm:completed' => 'checkCircle',
        'mod_scorm:failed' => 'failure',
        'mod_scorm:incomplete' => 'alert',
        'mod_scorm:notattempted' => 'circle',
        'mod_scorm:passed' => 'checkCircle',
        'mod_scorm:suspend' => 'pause',
        'tool_courserating:star' => 'star',
        'tool_courserating:star-half' => 'star',
        'tool_courserating:star-o' => 'star',
    ];

    /**
     * Keywords used for every remaining pix icon.
     *
     * More specific terms must appear before generic terms.
     */
    private const KEYWORD_ICONS = [
        'arrow-left' => 'arrowLeft',
        'arrow-right' => 'arrowRight',
        'arrow-up' => 'arrowUp',
        'arrow-down' => 'arrowDown',
        'chevron-left' => 'chevronLeft',
        'chevron-right' => 'chevronRight',
        'chevron-down' => 'chevronDown',
        'chevron-up' => 'chevronUp',
        'collapsed' => 'chevronRight',
        'expanded' => 'chevronDown',
        'certificate' => 'certificate',
        'completion' => 'checkCircle',
        'dashboard' => 'dashboard',
        'download' => 'download',
        'external' => 'externalLink',
        'feedback' => 'message',
        'loading' => 'spinner',
        'previous' => 'chevronLeft',
        'next' => 'chevronRight',
        'permission' => 'shield',
        'restore' => 'restore',
        'contentbank' => 'archive',
        'documentation' => 'book',
        'institution' => 'institution',
        'learningpath' => 'workflow',
        'notification' => 'bell',
        'participant' => 'group',
        'question' => 'help',
        'required' => 'required',
        'life-ring' => 'help',
        'support' => 'help',
        'settings' => 'settings',
        'company' => 'building',
        'department' => 'building',
        'archive' => 'archive',
        'award' => 'award',
        'badge' => 'award',
        'book' => 'book',
        'calendar' => 'calendar',
        'chart' => 'chart',
        'check' => 'check',
        'close' => 'close',
        'course' => 'course',
        'delete' => 'trash',
        'edit' => 'edit',
        'email' => 'mail',
        'expand' => 'expand',
        'export' => 'fileExport',
        'file' => 'file',
        'filter' => 'filter',
        'folder' => 'folder',
        'language' => 'language',
        'location' => 'mapPin',
        'grade' => 'list',
        'group' => 'group',
        'help' => 'help',
        'home' => 'home',
        'import' => 'fileImport',
        'info' => 'info',
        'key' => 'key',
        'link' => 'link',
        'list' => 'list',
        'lock' => 'lock',
        'login' => 'key',
        'logout' => 'logout',
        'menu' => 'menu',
        'message' => 'message',
        'markasread' => 'check',
        'more' => 'more',
        'move' => 'workflow',
        'pause' => 'pause',
        'play' => 'play',
        'print' => 'print',
        'refresh' => 'refresh',
        'reload' => 'refresh',
        'report' => 'report',
        'save' => 'save',
        'search' => 'search',
        'show' => 'eye',
        'star' => 'star',
        'tag' => 'tag',
        'time' => 'clock',
        'upload' => 'upload',
        'user' => 'user',
        'video' => 'video',
        'warning' => 'alert',
    ];

    /**
     * Legacy Font Awesome classes emitted directly by upstream IOMAD templates.
     */
    private const LEGACY_CLASS_MAP = [
        'fa-address-book' => 'user',
        'fa-address-card' => 'user',
        'fa-align-center' => 'list',
        'fa-align-justify' => 'list',
        'fa-align-left' => 'list',
        'fa-align-right' => 'list',
        'fa-anchor' => 'link',
        'fa-angle-down' => 'chevronDown',
        'fa-angle-left' => 'chevronLeft',
        'fa-angle-right' => 'chevronRight',
        'fa-angle-up' => 'chevronUp',
        'fa-angles-down' => 'arrowDown',
        'fa-angles-left' => 'arrowLeft',
        'fa-angles-right' => 'arrowRight',
        'fa-angles-up' => 'arrowUp',
        'fa-area-chart' => 'chart',
        'fa-arrow-circle-o-down' => 'arrowDown',
        'fa-arrow-down' => 'arrowDown',
        'fa-arrow-down-long' => 'arrowDown',
        'fa-arrow-down-short-wide' => 'sort',
        'fa-arrow-down-wide-short' => 'sort',
        'fa-arrow-left' => 'arrowLeft',
        'fa-arrow-right' => 'arrowRight',
        'fa-arrow-right-from-bracket' => 'logout',
        'fa-arrow-right-to-bracket' => 'key',
        'fa-arrow-rotate-left' => 'restore',
        'fa-arrow-rotate-right' => 'refresh',
        'fa-arrow-turn-up' => 'arrowUp',
        'fa-arrow-up' => 'arrowUp',
        'fa-arrow-up-from-bracket' => 'upload',
        'fa-arrow-up-long' => 'arrowUp',
        'fa-arrow-up-right-from-square' => 'externalLink',
        'fa-arrow-up-short-wide' => 'sort',
        'fa-arrows' => 'workflow',
        'fa-arrows-left-right' => 'workflow',
        'fa-arrows-left-right-to-line' => 'workflow',
        'fa-arrows-rotate' => 'refresh',
        'fa-arrows-to-circle' => 'workflow',
        'fa-arrows-up-down' => 'workflow',
        'fa-arrows-up-down-left-right' => 'workflow',
        'fa-asterisk' => 'required',
        'fa-audio-description' => 'volume',
        'fa-award' => 'award',
        'fa-ban' => 'ban',
        'fa-bar-chart-o' => 'chart',
        'fa-bars' => 'menu',
        'fa-bell' => 'bell',
        'fa-bolt' => 'activity',
        'fa-book' => 'book',
        'fa-book-bookmark' => 'book',
        'fa-book-open' => 'book',
        'fa-bookmark' => 'book',
        'fa-border-all' => 'dashboard',
        'fa-briefcase' => 'briefcase',
        'fa-building' => 'building',
        'fa-building-circle-arrow-right' => 'building',
        'fa-building-columns' => 'institution',
        'fa-bullhorn' => 'bullhorn',
        'fa-calculator' => 'list',
        'fa-calendar' => 'calendar',
        'fa-calendar-check' => 'calendar',
        'fa-calendar-plus' => 'calendar',
        'fa-caret-down' => 'chevronDown',
        'fa-caret-right' => 'chevronRight',
        'fa-caret-up' => 'chevronUp',
        'fa-cart-shopping' => 'cart',
        'fa-certificate' => 'certificate',
        'fa-chart-bar' => 'chart',
        'fa-chart-column' => 'chart',
        'fa-chart-line' => 'report',
        'fa-check' => 'check',
        'fa-check-circle' => 'checkCircle',
        'fa-check-double' => 'checkCircle',
        'fa-check-square-o' => 'checkCircle',
        'fa-check-to-slot' => 'checkCircle',
        'fa-chevron-circle-left' => 'chevronLeft',
        'fa-chevron-circle-right' => 'chevronRight',
        'fa-circle-check' => 'checkCircle',
        'fa-chevron-down' => 'chevronDown',
        'fa-chevron-left' => 'chevronLeft',
        'fa-chevron-right' => 'chevronRight',
        'fa-chevron-up' => 'chevronUp',
        'fa-circle' => 'circle',
        'fa-circle-arrow-down' => 'arrowDown',
        'fa-circle-dot' => 'circle',
        'fa-circle-exclamation' => 'alert',
        'fa-circle-info' => 'info',
        'fa-circle-minus' => 'close',
        'fa-circle-notch' => 'spinner',
        'fa-circle-o' => 'circle',
        'fa-circle-o-notch' => 'spinner',
        'fa-circle-pause' => 'pause',
        'fa-circle-play' => 'play',
        'fa-circle-plus' => 'add',
        'fa-circle-question' => 'help',
        'fa-circle-user' => 'user',
        'fa-circle-xmark' => 'failure',
        'fa-clipboard' => 'clipboard',
        'fa-clipboard-check' => 'form',
        'fa-clipboard-user' => 'user',
        'fa-clock' => 'clock',
        'fa-clock-o' => 'clock',
        'fa-clock-rotate-left' => 'restore',
        'fa-clone' => 'copy',
        'fa-cloud' => 'cloud',
        'fa-cloud-upload' => 'upload',
        'fa-code' => 'code',
        'fa-cog' => 'settings',
        'fa-comment' => 'message',
        'fa-commenting-o' => 'message',
        'fa-comments' => 'message',
        'fa-compress' => 'compress',
        'fa-copy' => 'copy',
        'fa-credit-card' => 'creditCard',
        'fa-crosshairs' => 'mapPin',
        'fa-cubes' => 'package',
        'fa-database' => 'database',
        'fa-delete-left' => 'close',
        'fa-diagram-project' => 'workflow',
        'fa-dollar-sign' => 'creditCard',
        'fa-download' => 'download',
        'fa-ear-listen' => 'volume',
        'fa-earth-americas' => 'globe',
        'fa-edit' => 'edit',
        'fa-ellipsis' => 'more',
        'fa-ellipsis-h' => 'more',
        'fa-ellipsis-v' => 'more',
        'fa-ellipsis-vertical' => 'more',
        'fa-envelope' => 'mail',
        'fa-envelope-open' => 'mail',
        'fa-eraser' => 'trash',
        'fa-exclamation' => 'alert',
        'fa-exclamation-circle' => 'alert',
        'fa-expand' => 'expand',
        'fa-external-link' => 'externalLink',
        'fa-eye' => 'eye',
        'fa-eye-dropper' => 'palette',
        'fa-eye-slash' => 'eyeOff',
        'fa-face-frown' => 'failure',
        'fa-face-smile' => 'smile',
        'fa-file' => 'file',
        'fa-file-csv' => 'fileImport',
        'fa-file-circle-minus' => 'trash',
        'fa-file-circle-plus' => 'add',
        'fa-file-circle-xmark' => 'failure',
        'fa-file-export' => 'fileExport',
        'fa-file-import' => 'fileImport',
        'fa-file-invoice' => 'file',
        'fa-file-pdf' => 'file',
        'fa-file-pen' => 'edit',
        'fa-file-signature' => 'edit',
        'fa-file-text' => 'file',
        'fa-file-video' => 'video',
        'fa-file-zipper' => 'archive',
        'fa-film' => 'video',
        'fa-filter' => 'filter',
        'fa-flag' => 'flag',
        'fa-flag-checkered' => 'flag',
        'fa-floppy-disk' => 'save',
        'fa-folder' => 'folder',
        'fa-folder-open' => 'folder',
        'fa-folder-plus' => 'folderPlus',
        'fa-folder-tree' => 'workflow',
        'fa-futbol' => 'activity',
        'fa-gauge' => 'dashboard',
        'fa-gauge-high' => 'dashboard',
        'fa-gear' => 'settings',
        'fa-globe' => 'globe',
        'fa-graduation-cap' => 'course',
        'fa-grip-vertical' => 'workflow',
        'fa-group' => 'group',
        'fa-hammer' => 'settings',
        'fa-hand-pointer' => 'user',
        'fa-hard-drive' => 'database',
        'fa-hashtag' => 'tag',
        'fa-highlighter' => 'edit',
        'fa-history' => 'restore',
        'fa-home' => 'home',
        'fa-house' => 'home',
        'fa-hourglass' => 'clock',
        'fa-id-badge' => 'user',
        'fa-image' => 'image',
        'fa-inbox' => 'mail',
        'fa-info-circle' => 'info',
        'fa-key' => 'key',
        'fa-language' => 'language',
        'fa-laptop-file' => 'file',
        'fa-layer-group' => 'workflow',
        'fa-leaf' => 'leaf',
        'fa-legal' => 'institution',
        'fa-life-ring' => 'help',
        'fa-link' => 'link',
        'fa-link-slash' => 'failure',
        'fa-list' => 'list',
        'fa-list-alt' => 'list',
        'fa-list-check' => 'form',
        'fa-list-ol' => 'list',
        'fa-list-ul' => 'list',
        'fa-location-dot' => 'mapPin',
        'fa-lock' => 'lock',
        'fa-lock-open' => 'key',
        'fa-low-vision' => 'eyeOff',
        'fa-magnifying-glass' => 'search',
        'fa-magnifying-glass-plus' => 'search',
        'fa-map-marker' => 'mapPin',
        'fa-map-signs' => 'mapPin',
        'fa-maximize' => 'expand',
        'fa-meh-o' => 'smile',
        'fa-message' => 'message',
        'fa-microchip' => 'settings',
        'fa-microphone-slash' => 'volume',
        'fa-minus' => 'close',
        'fa-mobile' => 'monitor',
        'fa-mobile-screen' => 'monitor',
        'fa-money' => 'creditCard',
        'fa-network-wired' => 'workflow',
        'fa-newspaper' => 'file',
        'fa-object-group' => 'workflow',
        'fa-object-ungroup' => 'workflow',
        'fa-palette' => 'palette',
        'fa-pager' => 'list',
        'fa-paper-plane' => 'message',
        'fa-paperclip' => 'paperclip',
        'fa-paste' => 'clipboard',
        'fa-pause' => 'pause',
        'fa-pen' => 'edit',
        'fa-pen-clip' => 'edit',
        'fa-pen-to-square' => 'edit',
        'fa-people-arrows' => 'group',
        'fa-people-group' => 'group',
        'fa-person' => 'user',
        'fa-photo-film' => 'image',
        'fa-pizza-slice' => 'coffee',
        'fa-plane' => 'mapPin',
        'fa-play' => 'play',
        'fa-plug' => 'puzzle',
        'fa-plus' => 'add',
        'fa-plus-square' => 'add',
        'fa-plus-square-o' => 'add',
        'fa-print' => 'print',
        'fa-puzzle-piece' => 'puzzle',
        'fa-question' => 'help',
        'fa-question-circle' => 'help',
        'fa-rectangle-list' => 'list',
        'fa-rectangle-xmark' => 'failure',
        'fa-refresh' => 'refresh',
        'fa-remove' => 'close',
        'fa-right-left' => 'workflow',
        'fa-right-to-bracket' => 'key',
        'fa-rotate' => 'refresh',
        'fa-rotate-left' => 'restore',
        'fa-rotate-right' => 'refresh',
        'fa-route' => 'workflow',
        'fa-rss' => 'activity',
        'fa-ruler-horizontal' => 'list',
        'fa-save' => 'save',
        'fa-scale-balanced' => 'institution',
        'fa-scissors' => 'cut',
        'fa-scroll' => 'certificate',
        'fa-shield' => 'shield',
        'fa-site-support' => 'help',
        'fa-shapes' => 'shapes',
        'fa-share' => 'externalLink',
        'fa-share-alt' => 'externalLink',
        'fa-share-from-square' => 'externalLink',
        'fa-smile' => 'smile',
        'fa-sort' => 'sort',
        'fa-sort-asc' => 'arrowUp',
        'fa-sort-desc' => 'arrowDown',
        'fa-sort-down' => 'arrowDown',
        'fa-sort-up' => 'arrowUp',
        'fa-spinner' => 'spinner',
        'fa-square' => 'circle',
        'fa-square-arrow-up-right' => 'externalLink',
        'fa-square-check' => 'checkCircle',
        'fa-square-pen' => 'edit',
        'fa-square-plus' => 'add',
        'fa-star' => 'star',
        'fa-star-half-full' => 'star',
        'fa-star-o' => 'star',
        'fa-stop' => 'failure',
        'fa-store' => 'store',
        'fa-store-slash' => 'failure',
        'fa-table' => 'dashboard',
        'fa-table-cells' => 'dashboard',
        'fa-table-cells-large' => 'dashboard',
        'fa-table-list' => 'list',
        'fa-tags' => 'tag',
        'fa-thumbs-up' => 'checkCircle',
        'fa-thumbtack' => 'mapPin',
        'fa-times' => 'close',
        'fa-toggle-off' => 'circle',
        'fa-toggle-on' => 'checkCircle',
        'fa-trash' => 'trash',
        'fa-trash-can' => 'trash',
        'fa-trash-can-arrow-up' => 'restore',
        'fa-trash-o' => 'trash',
        'fa-triangle-exclamation' => 'alert',
        'fa-trophy' => 'trophy',
        'fa-truck' => 'store',
        'fa-turn-down' => 'arrowDown',
        'fa-turn-up' => 'arrowUp',
        'fa-universal-access' => 'user',
        'fa-unlock' => 'key',
        'fa-unlock-keyhole' => 'key',
        'fa-up-down-left-right' => 'workflow',
        'fa-up-right-and-down-left-from-center' => 'expand',
        'fa-up-right-from-square' => 'externalLink',
        'fa-upload' => 'upload',
        'fa-user' => 'user',
        'fa-user-check' => 'user',
        'fa-user-circle-o' => 'user',
        'fa-user-group' => 'group',
        'fa-user-lock' => 'lock',
        'fa-user-plus' => 'userAdd',
        'fa-user-secret' => 'shield',
        'fa-user-tag' => 'user',
        'fa-user-tie' => 'user',
        'fa-user-xmark' => 'failure',
        'fa-users' => 'group',
        'fa-users-gear' => 'group',
        'fa-users-line' => 'group',
        'fa-verification-code' => 'shield',
        'fa-verify-form' => 'form',
        'fa-video' => 'video',
        'fa-volume-high' => 'volume',
        'fa-wand-magic-sparkles' => 'wand',
        'fa-warning' => 'alert',
        'fa-window-restore' => 'restore',
        'fa-wrench' => 'settings',
        'fa-xmark' => 'close',
    ];

    /**
     * Resolve a Moodle pix icon to a semantic sprite symbol.
     *
     * @param string|null $component Moodle component.
     * @param string $pix Pix icon name.
     * @return string
     */
    public static function resolve(?string $component, string $pix): string {
        $component = self::normalize_component($component);
        $pix = trim($pix, '/');
        $key = $component . ':' . $pix;

        if (isset(self::ICON_OVERRIDES[$key])) {
            return self::ICON_OVERRIDES[$key];
        }
        if (($pix === 'icon' || $pix === 'monologo') && isset(self::PROJECT_COMPONENTS[$component])) {
            return self::PROJECT_COMPONENTS[$component];
        }
        if (($pix === 'icon' || $pix === 'monologo') && isset(self::COMPONENT_ICONS[$component])) {
            return self::COMPONENT_ICONS[$component];
        }

        $search = strtolower(str_replace(['_', '/'], '-', $pix));
        foreach (self::KEYWORD_ICONS as $keyword => $icon) {
            if (str_contains($search, $keyword)) {
                return $icon;
            }
        }

        $type = strstr($component, '_', true);
        $resolved = self::TYPE_FALLBACKS[$type ?: ''] ?? 'activity';
        return svg_icon_library::has($resolved) ? $resolved : 'activity';
    }

    /**
     * Return project component mappings for contract tests and documentation.
     *
     * @return array<string, string>
     */
    public static function project_components(): array {
        return self::PROJECT_COMPONENTS;
    }

    /**
     * Return browser component mappings for activity and plugin image icons.
     *
     * @return array<string, string>
     */
    public static function client_component_map(): array {
        $map = self::COMPONENT_ICONS + self::PROJECT_COMPONENTS;
        foreach (array_keys(\core_component::get_plugin_types()) as $type) {
            foreach (array_keys(\core_component::get_plugin_list($type)) as $name) {
                $component = \core_component::normalize_componentname($type . '_' . $name);
                $map[$component] ??= self::TYPE_FALLBACKS[$type] ?? 'activity';
            }
        }
        ksort($map);
        return $map;
    }

    /**
     * Return the reviewed legacy Font Awesome migration map.
     *
     * @return array<string, string>
     */
    public static function legacy_class_map(): array {
        return self::LEGACY_CLASS_MAP;
    }

    /**
     * Normalize Moodle's historical core component aliases.
     *
     * @param string|null $component Component name.
     * @return string
     */
    private static function normalize_component(?string $component): string {
        if ($component === null || $component === '' || $component === 'moodle' || $component === 'theme') {
            return 'core';
        }
        return \core_component::normalize_componentname($component);
    }
}
